//! Some resource strings.

/// The default C++ template.
pub static CPP_TEMPLATE_0: &'static str = r"
// {##}
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <vector>
#include <cmath>
#include <stack>
#include <queue>
using namespace std;

static const int MAXN = 1e5+114514;

int main() {
    return 0;
}

";

/// An alternative template.
pub static CPP_TEMPLATE_1: &'static str = r"
// {##}
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

static const int MAXN = 1e5+114514;

int main() {
}

";

/// Default dp template.
pub static CPP_DP_TEMPLATE_0: &'static str = r"
// {##}
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <vector>
#include <cmath>
#include <stack>
#include <queue>
using namespace std;

static const int MAXN = 1e5+114514;
int dp[MAXN];

int main() {
    return 0;
}

";

/// An alternative template.
pub static CPP_DP_TEMPLATE_1: &'static str = r"
// {##}
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

static const int MAXN = 1e5+114514;
int dp[MAXN];

int main() {
}

";